site_name: Data Lake SMS Rio

nav:
  - Home:
    - Olá!: index.md
    - Governança: governanca.md
    - Acessos: acessos.md
  - Guia de Uso: 
      - Organização dos dados no Data Lake : guia-uso/organizacao-dados.md
      - Acessando os dados:
        - Consultas no BigQuery: guia-uso/consultas-diretas.md
        - Acessando por outras plataformas: guia-uso/outras-formas.md
        - Ambiente Sandbox: guia-uso/sandbox.md
  - Guia de Desenvolvedores:
      - Visão Geral da Infraestrutura: guia-desenvolvedores/infraestrutura.md
      - Contribuindo para o projeto: guia-desenvolvedores/contribuindo-projeto.md
      - Campos: guia-desenvolvedores/campos.md
  - Sobre: sobre/sobre.md

theme:
  name: material
  custom_dir: overrides 
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    primary: blue
    accent: orange
  font:
    - text: DM Sans
    - code: JetBrains Mono
  language: pt
  copyright: Copyright &copy; 2026 Data Lake SMS Rio # Exemplo de aviso de direitos autorais
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.integrate
    - content.tabs.link
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand


extra:
  version: 2.0
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/SRVQPcJb
    - icon: fontawesome/brands/github
      link: https://github.com/prefeitura-rio
  generator: false
# repo_url: https://github.com/prefeitura-rio/docs-sms
# repo_name: prefeitura-rio/docs-sms

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.blocks.caption
  - md_in_html