site_name: Comitê de Inovação e Tecnologia (S/CIT)
site_url: https://herianc.github.io/sms-datalake-docs
nav:
  - Início:
    - Apresentação: index.md
    - Governança: governanca.md
    - Acessos: acessos.md
  - Guia de Uso: 
      - Organização dos dados no Data Lake : guia-uso/organizacao-dados.md
      - Acessando os dados:
        - Consultas no BigQuery: guia-uso/consultas-diretas.md
        - Acessando por outras plataformas: guia-uso/outras-formas.md
      - Ambiente Sandbox:
        - O que é? : guia-uso/sandbox.md
        - Operações Básicas: guia-uso/sandbox-operacoes-basicas.md
  - Guia de Desenvolvimento:
      - Visão Geral da Infraestrutura: guia-desenvolvedores/infraestrutura.md
      - Contribuindo para o projeto: guia-desenvolvedores/contribuindo-projeto.md
      - Campos: guia-desenvolvedores/campos.md
  - Sobre: 
      - Comitê de Inovação e Tecnologia: sobre/cit.md
      - Produtos: 
        - Histórico Clínico Integrado: sobre/hci.md
        - Farmácia Digital:  sobre/farmacia-digital.md
theme:
  name: material
  custom_dir: overrides 
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    primary: custom
  font:
    text: Open Sans
    code: JetBrains Mono
  language: pt
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.integrate
    - content.tabs.link


plugins:
  - search
  - meta
  - social:
      cards_layout_options:
        font_family: Open Sans


extra:
  version: 2.0
  social:
    - icon: fontawesome/solid/globe
      link: https://saude.prefeitura.rio/
    - icon: fontawesome/brands/github
      link: https://github.com/prefeitura-rio
    - icon: fontawesome/brands/discord
      link: https://discord.gg/SRVQPcJb


  generator: false
# repo_url: https://github.com/prefeitura-rio/docs-sms
# repo_name: prefeitura-rio/docs-sms

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.blocks.caption
  - md_in_html
  - pymdownx.keys

extra_css:
  - stylesheets/extra.css